DELIMITER $$

DROP PROCEDURE IF EXISTS `BuildTmpPrintouts` $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `BuildTmpPrintouts`()
BEGIN

SET @CountSame:=0;
SET @LastDataString:='';
SET @LastID:='';
SET @LastUpdateDate:='1900-01-01';
SET @OuterCountSame:=1;
SET @OuterLastID = '';

INSERT INTO tmpPrintouts

SELECT ID, OrigID, DataString, UpdateDate, Version,
  Case when OrigID = @OuterLastID then
      @OuterCountSame := @OuterCountSame + 1
    else
      @OuterCountSame := 1
    end as pagenum,
  (@OuterLastID := OrigID)

FROM (
SELECT *, 
  Case when DataString = @LastDataString AND @LastID = OrigID then
      @CountSame := @CountSame + 1
    else
      @CountSame := 0
    end as version,
  (@LastID := OrigID),
  (@LastUpdateDate := UpdateDate),
  (@LastDataString := DataString)
FROM (

SELECT ID, OrigID,
CONCAT(FoodStamps, '-', IFNULL(CAST(Line1_Monthly AS UNSIGNED), ''), '-', IFNULL(CAST(Line1_Weekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line1_BiWeekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line1_Yearly AS UNSIGNED), ''), '-', IFNULL(CAST(Line1_Income AS UNSIGNED), ''),
IFNULL(CAST(Line2_Monthly AS UNSIGNED), ''), '-', IFNULL(CAST(Line2_Weekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line2_BiWeekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line2_Yearly AS UNSIGNED), ''), '-', IFNULL(CAST(Line2_Income AS UNSIGNED), ''),
IFNULL(CAST(Line3_Monthly AS UNSIGNED), ''), '-', IFNULL(CAST(Line3_Weekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line3_BiWeekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line3_Yearly AS UNSIGNED), ''), '-', IFNULL(CAST(Line3_Income AS UNSIGNED), ''),
IFNULL(CAST(Line4_Monthly AS UNSIGNED), ''), '-', IFNULL(CAST(Line4_Weekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line4_BiWeekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line4_Yearly AS UNSIGNED), ''), '-', IFNULL(CAST(Line4_Income AS UNSIGNED), ''),
IFNULL(CAST(Line5_Monthly AS UNSIGNED), ''), '-', IFNULL(CAST(Line5_Weekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line5_BiWeekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line5_Yearly AS UNSIGNED), ''), '-', IFNULL(CAST(Line5_Income AS UNSIGNED), ''),
IFNULL(CAST(Line6_Monthly AS UNSIGNED), ''), '-', IFNULL(CAST(Line6_Weekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line6_BiWeekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line6_Yearly AS UNSIGNED), ''), '-', IFNULL(CAST(Line6_Income AS UNSIGNED), ''),
IFNULL(CAST(Line7_Monthly AS UNSIGNED), ''), '-', IFNULL(CAST(Line7_Weekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line7_BiWeekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line7_Yearly AS UNSIGNED), ''), '-', IFNULL(CAST(Line7_Income AS UNSIGNED), ''),
IFNULL(CAST(Line8_Monthly AS UNSIGNED), ''), '-', IFNULL(CAST(Line8_Weekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line8_BiWeekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line8_Yearly AS UNSIGNED), ''), '-', IFNULL(CAST(Line8_Income AS UNSIGNED), ''),
IFNULL(CAST(Line9_Monthly AS UNSIGNED), ''), '-', IFNULL(CAST(Line9_Weekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line9_BiWeekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line9_Yearly AS UNSIGNED), ''), '-', IFNULL(CAST(Line9_Income AS UNSIGNED), ''),
IFNULL(CAST(Line10_Monthly AS UNSIGNED), ''), '-', IFNULL(CAST(Line10_Weekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line10_BiWeekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line10_Yearly AS UNSIGNED), ''), '-', IFNULL(CAST(Line10_Income AS UNSIGNED), ''),
IFNULL(CAST(Line11_Monthly AS UNSIGNED), ''), '-', IFNULL(CAST(Line11_Weekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line11_BiWeekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line11_Yearly AS UNSIGNED), ''), '-', IFNULL(CAST(Line11_Income AS UNSIGNED), ''),
IFNULL(CAST(Line12_Monthly AS UNSIGNED), ''), '-', IFNULL(CAST(Line12_Weekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line12_BiWeekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line12_Yearly AS UNSIGNED), ''), '-', IFNULL(CAST(Line12_Income AS UNSIGNED), ''),
IFNULL(CAST(Line13_Monthly AS UNSIGNED), ''), '-', IFNULL(CAST(Line13_Weekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line13_BiWeekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line13_Yearly AS UNSIGNED), ''), '-', IFNULL(CAST(Line13_Income AS UNSIGNED), ''),
IFNULL(CAST(Line14_Monthly AS UNSIGNED), ''), '-', IFNULL(CAST(Line14_Weekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line14_BiWeekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line14_Yearly AS UNSIGNED), ''), '-', IFNULL(CAST(Line14_Income AS UNSIGNED), ''),
IFNULL(CAST(Line15_Monthly AS UNSIGNED), ''), '-', IFNULL(CAST(Line15_Weekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line15_BiWeekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line15_Yearly AS UNSIGNED), ''), '-', IFNULL(CAST(Line15_Income AS UNSIGNED), ''),
IFNULL(CAST(Line16_Monthly AS UNSIGNED), ''), '-', IFNULL(CAST(Line16_Weekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line16_BiWeekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line16_Yearly AS UNSIGNED), ''), '-', IFNULL(CAST(Line16_Income AS UNSIGNED), ''),
IFNULL(CAST(Line17_Monthly AS UNSIGNED), ''), '-', IFNULL(CAST(Line17_Weekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line17_BiWeekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line17_Yearly AS UNSIGNED), ''), '-', IFNULL(CAST(Line17_Income AS UNSIGNED), ''),
IFNULL(CAST(Line18_Monthly AS UNSIGNED), ''), '-', IFNULL(CAST(Line18_Weekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line18_BiWeekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line18_Yearly AS UNSIGNED), ''), '-', IFNULL(CAST(Line18_Income AS UNSIGNED), ''),
IFNULL(CAST(Line19_Monthly AS UNSIGNED), ''), '-', IFNULL(CAST(Line19_Weekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line19_BiWeekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line19_Yearly AS UNSIGNED), ''), '-', IFNULL(CAST(Line19_Income AS UNSIGNED), ''),
IFNULL(CAST(Line20_Monthly AS UNSIGNED), ''), '-', IFNULL(CAST(Line20_Weekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line20_BiWeekly AS UNSIGNED), ''), '-', IFNULL(CAST(Line20_Yearly AS UNSIGNED), ''), '-', IFNULL(CAST(Line20_Income AS UNSIGNED), '')) as DataString,
UpdateDate
 FROM (
SELECT
1000000.`ID`,
`intake`.`LastName`,
`intake`.`FirstName`,
`intake`.`Address`,
`intake`.`City`,
`intake`.`State`,
`intake`.`Phone`,
`intake`.`AptNumber`,
`intake`.`FoodStamps`,
`intake`.`FoodStampAmount`,
`intake`.`WorkerName`,
`intake`.`DoB`,
`intake`.`Zip`,
`intake`.`Line1_Name`,
`intake`.`Line1_Age`,
`intake`.`Line1_Sex`,
`intake`.`Line1_Income`,
`intake`.`Line1_Monthly`,
`intake`.`Line1_Weekly`,
`intake`.`Line1_BiWeekly`,
`intake`.`Line1_Yearly`,
`intake`.`Line1_Medicaid`,
`intake`.`Line1_TANF`,
`intake`.`Line1_SSI`,
`intake`.`Line1_Other`,
`intake`.`Line2_Name`,
`intake`.`Line2_Age`,
`intake`.`Line2_Sex`,
`intake`.`Line2_Income`,
`intake`.`Line2_Monthly`,
`intake`.`Line2_Weekly`,
`intake`.`Line2_BiWeekly`,
`intake`.`Line2_Yearly`,
`intake`.`Line2_Medicaid`,
`intake`.`Line2_TANF`,
`intake`.`Line2_SSI`,
`intake`.`Line2_Other`,
`intake`.`Line3_Name`,
`intake`.`Line3_Age`,
`intake`.`Line3_Sex`,
`intake`.`Line3_Income`,
`intake`.`Line3_Monthly`,
`intake`.`Line3_Weekly`,
`intake`.`Line3_BiWeekly`,
`intake`.`Line3_Yearly`,
`intake`.`Line3_Medicaid`,
`intake`.`Line3_TANF`,
`intake`.`Line3_SSI`,
`intake`.`Line3_Other`,
`intake`.`Line4_Name`,
`intake`.`Line4_Age`,
`intake`.`Line4_Sex`,
`intake`.`Line4_Income`,
`intake`.`Line4_Monthly`,
`intake`.`Line4_Weekly`,
`intake`.`Line4_BiWeekly`,
`intake`.`Line4_Yearly`,
`intake`.`Line4_Medicaid`,
`intake`.`Line4_TANF`,
`intake`.`Line4_SSI`,
`intake`.`Line4_Other`,
`intake`.`Line5_Name`,
`intake`.`Line5_Age`,
`intake`.`Line5_Sex`,
`intake`.`Line5_Income`,
`intake`.`Line5_Monthly`,
`intake`.`Line5_Weekly`,
`intake`.`Line5_BiWeekly`,
`intake`.`Line5_Yearly`,
`intake`.`Line5_Medicaid`,
`intake`.`Line5_TANF`,
`intake`.`Line5_SSI`,
`intake`.`Line5_Other`,
`intake`.`Line6_Name`,
`intake`.`Line6_Age`,
`intake`.`Line6_Sex`,
`intake`.`Line6_Income`,
`intake`.`Line6_Monthly`,
`intake`.`Line6_Weekly`,
`intake`.`Line6_BiWeekly`,
`intake`.`Line6_Yearly`,
`intake`.`Line6_Medicaid`,
`intake`.`Line6_TANF`,
`intake`.`Line6_SSI`,
`intake`.`Line6_Other`,
`intake`.`Line7_Name`,
`intake`.`Line7_Age`,
`intake`.`Line7_Sex`,
`intake`.`Line7_Income`,
`intake`.`Line7_Monthly`,
`intake`.`Line7_Weekly`,
`intake`.`Line7_BiWeekly`,
`intake`.`Line7_Yearly`,
`intake`.`Line7_Medicaid`,
`intake`.`Line7_TANF`,
`intake`.`Line7_SSI`,
`intake`.`Line7_Other`,
`intake`.`Line8_Name`,
`intake`.`Line8_Age`,
`intake`.`Line8_Sex`,
`intake`.`Line8_Income`,
`intake`.`Line8_Monthly`,
`intake`.`Line8_Weekly`,
`intake`.`Line8_BiWeekly`,
`intake`.`Line8_Yearly`,
`intake`.`Line8_Medicaid`,
`intake`.`Line8_TANF`,
`intake`.`Line8_SSI`,
`intake`.`Line8_Other`,
`intake`.`Line9_Name`,
`intake`.`Line9_Age`,
`intake`.`Line9_Sex`,
`intake`.`Line9_Income`,
`intake`.`Line9_Monthly`,
`intake`.`Line9_Weekly`,
`intake`.`Line9_BiWeekly`,
`intake`.`Line9_Yearly`,
`intake`.`Line9_Medicaid`,
`intake`.`Line9_TANF`,
`intake`.`Line9_SSI`,
`intake`.`Line9_Other`,
`intake`.`Line10_Name`,
`intake`.`Line10_Age`,
`intake`.`Line10_Sex`,
`intake`.`Line10_Income`,
`intake`.`Line10_Monthly`,
`intake`.`Line10_Weekly`,
`intake`.`Line10_BiWeekly`,
`intake`.`Line10_Yearly`,
`intake`.`Line10_Medicaid`,
`intake`.`Line10_TANF`,
`intake`.`Line10_SSI`,
`intake`.`Line10_Other`,
`intake`.`Line11_Name`,
`intake`.`Line11_Age`,
`intake`.`Line11_Sex`,
`intake`.`Line11_Income`,
`intake`.`Line11_Monthly`,
`intake`.`Line11_Weekly`,
`intake`.`Line11_BiWeekly`,
`intake`.`Line11_Yearly`,
`intake`.`Line11_Medicaid`,
`intake`.`Line11_TANF`,
`intake`.`Line11_SSI`,
`intake`.`Line11_Other`,
`intake`.`Line12_Name`,
`intake`.`Line12_Age`,
`intake`.`Line12_Sex`,
`intake`.`Line12_Income`,
`intake`.`Line12_Monthly`,
`intake`.`Line12_Weekly`,
`intake`.`Line12_BiWeekly`,
`intake`.`Line12_Yearly`,
`intake`.`Line12_Medicaid`,
`intake`.`Line12_TANF`,
`intake`.`Line12_SSI`,
`intake`.`Line12_Other`,
`intake`.`Line13_Name`,
`intake`.`Line13_Age`,
`intake`.`Line13_Sex`,
`intake`.`Line13_Income`,
`intake`.`Line13_Monthly`,
`intake`.`Line13_Weekly`,
`intake`.`Line13_BiWeekly`,
`intake`.`Line13_Yearly`,
`intake`.`Line13_Medicaid`,
`intake`.`Line13_TANF`,
`intake`.`Line13_SSI`,
`intake`.`Line13_Other`,
`intake`.`Line14_Name`,
`intake`.`Line14_Age`,
`intake`.`Line14_Sex`,
`intake`.`Line14_Income`,
`intake`.`Line14_Monthly`,
`intake`.`Line14_Weekly`,
`intake`.`Line14_BiWeekly`,
`intake`.`Line14_Yearly`,
`intake`.`Line14_Medicaid`,
`intake`.`Line14_TANF`,
`intake`.`Line14_SSI`,
`intake`.`Line14_Other`,
`intake`.`Line15_Name`,
`intake`.`Line15_Age`,
`intake`.`Line15_Sex`,
`intake`.`Line15_Income`,
`intake`.`Line15_Monthly`,
`intake`.`Line15_Weekly`,
`intake`.`Line15_BiWeekly`,
`intake`.`Line15_Yearly`,
`intake`.`Line15_Medicaid`,
`intake`.`Line15_TANF`,
`intake`.`Line15_SSI`,
`intake`.`Line15_Other`,
`intake`.`Line16_Name`,
`intake`.`Line16_Age`,
`intake`.`Line16_Sex`,
`intake`.`Line16_Income`,
`intake`.`Line16_Monthly`,
`intake`.`Line16_Weekly`,
`intake`.`Line16_BiWeekly`,
`intake`.`Line16_Yearly`,
`intake`.`Line16_Medicaid`,
`intake`.`Line16_TANF`,
`intake`.`Line16_SSI`,
`intake`.`Line16_Other`,
`intake`.`Line17_Name`,
`intake`.`Line17_Age`,
`intake`.`Line17_Sex`,
`intake`.`Line17_Income`,
`intake`.`Line17_Monthly`,
`intake`.`Line17_Weekly`,
`intake`.`Line17_BiWeekly`,
`intake`.`Line17_Yearly`,
`intake`.`Line17_Medicaid`,
`intake`.`Line17_TANF`,
`intake`.`Line17_SSI`,
`intake`.`Line17_Other`,
`intake`.`Line18_Name`,
`intake`.`Line18_Age`,
`intake`.`Line18_Sex`,
`intake`.`Line18_Income`,
`intake`.`Line18_Monthly`,
`intake`.`Line18_Weekly`,
`intake`.`Line18_BiWeekly`,
`intake`.`Line18_Yearly`,
`intake`.`Line18_Medicaid`,
`intake`.`Line18_TANF`,
`intake`.`Line18_SSI`,
`intake`.`Line18_Other`,
`intake`.`Line19_Name`,
`intake`.`Line19_Age`,
`intake`.`Line19_Sex`,
`intake`.`Line19_Income`,
`intake`.`Line19_Monthly`,
`intake`.`Line19_Weekly`,
`intake`.`Line19_BiWeekly`,
`intake`.`Line19_Yearly`,
`intake`.`Line19_Medicaid`,
`intake`.`Line19_TANF`,
`intake`.`Line19_SSI`,
`intake`.`Line19_Other`,
`intake`.`Line20_Name`,
`intake`.`Line20_Age`,
`intake`.`Line20_Sex`,
`intake`.`Line20_Income`,
`intake`.`Line20_Monthly`,
`intake`.`Line20_Weekly`,
`intake`.`Line20_BiWeekly`,
`intake`.`Line20_Yearly`,
`intake`.`Line20_Medicaid`,
`intake`.`Line20_TANF`,
`intake`.`Line20_SSI`,
`intake`.`Line20_Other`,
`intake`.`Line21_Name`,
`intake`.`Line21_Age`,
`intake`.`Line21_Sex`,
`intake`.`Line21_Income`,
`intake`.`Line21_Monthly`,
`intake`.`Line21_Weekly`,
`intake`.`Line21_BiWeekly`,
`intake`.`Line21_Yearly`,
`intake`.`Line21_Medicaid`,
`intake`.`Line21_TANF`,
`intake`.`Line21_SSI`,
`intake`.`Line21_Other`,
`intake`.`Signature1`,
`intake`.`Signature2`,
`intake`.`Signature3`,
`intake`.`Signature4`,
`intake`.`Signature5`,
`intake`.`Signature6`,
`intake`.`Signature1Date`,
`intake`.`Signature2Date`,
`intake`.`Signature3Date`,
`intake`.`Signature4Date`,
`intake`.`Signature5Date`,
`intake`.`Signature6Date`,
NOW() AS `UpdateDate`,
ID AS `OrigID`
FROM `pantry`.`intake`
UNION ALL
SELECT
`intakelog`.`ID`,
`intakelog`.`LastName`,
`intakelog`.`FirstName`,
`intakelog`.`Address`,
`intakelog`.`City`,
`intakelog`.`State`,
`intakelog`.`Phone`,
`intakelog`.`AptNumber`,
`intakelog`.`FoodStamps`,
`intakelog`.`FoodStampAmount`,
`intakelog`.`WorkerName`,
`intakelog`.`DoB`,
`intakelog`.`Zip`,
`intakelog`.`Line1_Name`,
`intakelog`.`Line1_Age`,
`intakelog`.`Line1_Sex`,
`intakelog`.`Line1_Income`,
`intakelog`.`Line1_Monthly`,
`intakelog`.`Line1_Weekly`,
`intakelog`.`Line1_BiWeekly`,
`intakelog`.`Line1_Yearly`,
`intakelog`.`Line1_Medicaid`,
`intakelog`.`Line1_TANF`,
`intakelog`.`Line1_SSI`,
`intakelog`.`Line1_Other`,
`intakelog`.`Line2_Name`,
`intakelog`.`Line2_Age`,
`intakelog`.`Line2_Sex`,
`intakelog`.`Line2_Income`,
`intakelog`.`Line2_Monthly`,
`intakelog`.`Line2_Weekly`,
`intakelog`.`Line2_BiWeekly`,
`intakelog`.`Line2_Yearly`,
`intakelog`.`Line2_Medicaid`,
`intakelog`.`Line2_TANF`,
`intakelog`.`Line2_SSI`,
`intakelog`.`Line2_Other`,
`intakelog`.`Line3_Name`,
`intakelog`.`Line3_Age`,
`intakelog`.`Line3_Sex`,
`intakelog`.`Line3_Income`,
`intakelog`.`Line3_Monthly`,
`intakelog`.`Line3_Weekly`,
`intakelog`.`Line3_BiWeekly`,
`intakelog`.`Line3_Yearly`,
`intakelog`.`Line3_Medicaid`,
`intakelog`.`Line3_TANF`,
`intakelog`.`Line3_SSI`,
`intakelog`.`Line3_Other`,
`intakelog`.`Line4_Name`,
`intakelog`.`Line4_Age`,
`intakelog`.`Line4_Sex`,
`intakelog`.`Line4_Income`,
`intakelog`.`Line4_Monthly`,
`intakelog`.`Line4_Weekly`,
`intakelog`.`Line4_BiWeekly`,
`intakelog`.`Line4_Yearly`,
`intakelog`.`Line4_Medicaid`,
`intakelog`.`Line4_TANF`,
`intakelog`.`Line4_SSI`,
`intakelog`.`Line4_Other`,
`intakelog`.`Line5_Name`,
`intakelog`.`Line5_Age`,
`intakelog`.`Line5_Sex`,
`intakelog`.`Line5_Income`,
`intakelog`.`Line5_Monthly`,
`intakelog`.`Line5_Weekly`,
`intakelog`.`Line5_BiWeekly`,
`intakelog`.`Line5_Yearly`,
`intakelog`.`Line5_Medicaid`,
`intakelog`.`Line5_TANF`,
`intakelog`.`Line5_SSI`,
`intakelog`.`Line5_Other`,
`intakelog`.`Line6_Name`,
`intakelog`.`Line6_Age`,
`intakelog`.`Line6_Sex`,
`intakelog`.`Line6_Income`,
`intakelog`.`Line6_Monthly`,
`intakelog`.`Line6_Weekly`,
`intakelog`.`Line6_BiWeekly`,
`intakelog`.`Line6_Yearly`,
`intakelog`.`Line6_Medicaid`,
`intakelog`.`Line6_TANF`,
`intakelog`.`Line6_SSI`,
`intakelog`.`Line6_Other`,
`intakelog`.`Line7_Name`,
`intakelog`.`Line7_Age`,
`intakelog`.`Line7_Sex`,
`intakelog`.`Line7_Income`,
`intakelog`.`Line7_Monthly`,
`intakelog`.`Line7_Weekly`,
`intakelog`.`Line7_BiWeekly`,
`intakelog`.`Line7_Yearly`,
`intakelog`.`Line7_Medicaid`,
`intakelog`.`Line7_TANF`,
`intakelog`.`Line7_SSI`,
`intakelog`.`Line7_Other`,
`intakelog`.`Line8_Name`,
`intakelog`.`Line8_Age`,
`intakelog`.`Line8_Sex`,
`intakelog`.`Line8_Income`,
`intakelog`.`Line8_Monthly`,
`intakelog`.`Line8_Weekly`,
`intakelog`.`Line8_BiWeekly`,
`intakelog`.`Line8_Yearly`,
`intakelog`.`Line8_Medicaid`,
`intakelog`.`Line8_TANF`,
`intakelog`.`Line8_SSI`,
`intakelog`.`Line8_Other`,
`intakelog`.`Line9_Name`,
`intakelog`.`Line9_Age`,
`intakelog`.`Line9_Sex`,
`intakelog`.`Line9_Income`,
`intakelog`.`Line9_Monthly`,
`intakelog`.`Line9_Weekly`,
`intakelog`.`Line9_BiWeekly`,
`intakelog`.`Line9_Yearly`,
`intakelog`.`Line9_Medicaid`,
`intakelog`.`Line9_TANF`,
`intakelog`.`Line9_SSI`,
`intakelog`.`Line9_Other`,
`intakelog`.`Line10_Name`,
`intakelog`.`Line10_Age`,
`intakelog`.`Line10_Sex`,
`intakelog`.`Line10_Income`,
`intakelog`.`Line10_Monthly`,
`intakelog`.`Line10_Weekly`,
`intakelog`.`Line10_BiWeekly`,
`intakelog`.`Line10_Yearly`,
`intakelog`.`Line10_Medicaid`,
`intakelog`.`Line10_TANF`,
`intakelog`.`Line10_SSI`,
`intakelog`.`Line10_Other`,
`intakelog`.`Line11_Name`,
`intakelog`.`Line11_Age`,
`intakelog`.`Line11_Sex`,
`intakelog`.`Line11_Income`,
`intakelog`.`Line11_Monthly`,
`intakelog`.`Line11_Weekly`,
`intakelog`.`Line11_BiWeekly`,
`intakelog`.`Line11_Yearly`,
`intakelog`.`Line11_Medicaid`,
`intakelog`.`Line11_TANF`,
`intakelog`.`Line11_SSI`,
`intakelog`.`Line11_Other`,
`intakelog`.`Line12_Name`,
`intakelog`.`Line12_Age`,
`intakelog`.`Line12_Sex`,
`intakelog`.`Line12_Income`,
`intakelog`.`Line12_Monthly`,
`intakelog`.`Line12_Weekly`,
`intakelog`.`Line12_BiWeekly`,
`intakelog`.`Line12_Yearly`,
`intakelog`.`Line12_Medicaid`,
`intakelog`.`Line12_TANF`,
`intakelog`.`Line12_SSI`,
`intakelog`.`Line12_Other`,
`intakelog`.`Line13_Name`,
`intakelog`.`Line13_Age`,
`intakelog`.`Line13_Sex`,
`intakelog`.`Line13_Income`,
`intakelog`.`Line13_Monthly`,
`intakelog`.`Line13_Weekly`,
`intakelog`.`Line13_BiWeekly`,
`intakelog`.`Line13_Yearly`,
`intakelog`.`Line13_Medicaid`,
`intakelog`.`Line13_TANF`,
`intakelog`.`Line13_SSI`,
`intakelog`.`Line13_Other`,
`intakelog`.`Line14_Name`,
`intakelog`.`Line14_Age`,
`intakelog`.`Line14_Sex`,
`intakelog`.`Line14_Income`,
`intakelog`.`Line14_Monthly`,
`intakelog`.`Line14_Weekly`,
`intakelog`.`Line14_BiWeekly`,
`intakelog`.`Line14_Yearly`,
`intakelog`.`Line14_Medicaid`,
`intakelog`.`Line14_TANF`,
`intakelog`.`Line14_SSI`,
`intakelog`.`Line14_Other`,
`intakelog`.`Line15_Name`,
`intakelog`.`Line15_Age`,
`intakelog`.`Line15_Sex`,
`intakelog`.`Line15_Income`,
`intakelog`.`Line15_Monthly`,
`intakelog`.`Line15_Weekly`,
`intakelog`.`Line15_BiWeekly`,
`intakelog`.`Line15_Yearly`,
`intakelog`.`Line15_Medicaid`,
`intakelog`.`Line15_TANF`,
`intakelog`.`Line15_SSI`,
`intakelog`.`Line15_Other`,
`intakelog`.`Line16_Name`,
`intakelog`.`Line16_Age`,
`intakelog`.`Line16_Sex`,
`intakelog`.`Line16_Income`,
`intakelog`.`Line16_Monthly`,
`intakelog`.`Line16_Weekly`,
`intakelog`.`Line16_BiWeekly`,
`intakelog`.`Line16_Yearly`,
`intakelog`.`Line16_Medicaid`,
`intakelog`.`Line16_TANF`,
`intakelog`.`Line16_SSI`,
`intakelog`.`Line16_Other`,
`intakelog`.`Line17_Name`,
`intakelog`.`Line17_Age`,
`intakelog`.`Line17_Sex`,
`intakelog`.`Line17_Income`,
`intakelog`.`Line17_Monthly`,
`intakelog`.`Line17_Weekly`,
`intakelog`.`Line17_BiWeekly`,
`intakelog`.`Line17_Yearly`,
`intakelog`.`Line17_Medicaid`,
`intakelog`.`Line17_TANF`,
`intakelog`.`Line17_SSI`,
`intakelog`.`Line17_Other`,
`intakelog`.`Line18_Name`,
`intakelog`.`Line18_Age`,
`intakelog`.`Line18_Sex`,
`intakelog`.`Line18_Income`,
`intakelog`.`Line18_Monthly`,
`intakelog`.`Line18_Weekly`,
`intakelog`.`Line18_BiWeekly`,
`intakelog`.`Line18_Yearly`,
`intakelog`.`Line18_Medicaid`,
`intakelog`.`Line18_TANF`,
`intakelog`.`Line18_SSI`,
`intakelog`.`Line18_Other`,
`intakelog`.`Line19_Name`,
`intakelog`.`Line19_Age`,
`intakelog`.`Line19_Sex`,
`intakelog`.`Line19_Income`,
`intakelog`.`Line19_Monthly`,
`intakelog`.`Line19_Weekly`,
`intakelog`.`Line19_BiWeekly`,
`intakelog`.`Line19_Yearly`,
`intakelog`.`Line19_Medicaid`,
`intakelog`.`Line19_TANF`,
`intakelog`.`Line19_SSI`,
`intakelog`.`Line19_Other`,
`intakelog`.`Line20_Name`,
`intakelog`.`Line20_Age`,
`intakelog`.`Line20_Sex`,
`intakelog`.`Line20_Income`,
`intakelog`.`Line20_Monthly`,
`intakelog`.`Line20_Weekly`,
`intakelog`.`Line20_BiWeekly`,
`intakelog`.`Line20_Yearly`,
`intakelog`.`Line20_Medicaid`,
`intakelog`.`Line20_TANF`,
`intakelog`.`Line20_SSI`,
`intakelog`.`Line20_Other`,
`intakelog`.`Line21_Name`,
`intakelog`.`Line21_Age`,
`intakelog`.`Line21_Sex`,
`intakelog`.`Line21_Income`,
`intakelog`.`Line21_Monthly`,
`intakelog`.`Line21_Weekly`,
`intakelog`.`Line21_BiWeekly`,
`intakelog`.`Line21_Yearly`,
`intakelog`.`Line21_Medicaid`,
`intakelog`.`Line21_TANF`,
`intakelog`.`Line21_SSI`,
`intakelog`.`Line21_Other`,
`intakelog`.`Signature1`,
`intakelog`.`Signature2`,
`intakelog`.`Signature3`,
`intakelog`.`Signature4`,
`intakelog`.`Signature5`,
`intakelog`.`Signature6`,
`intakelog`.`Signature1Date`,
`intakelog`.`Signature2Date`,
`intakelog`.`Signature3Date`,
`intakelog`.`Signature4Date`,
`intakelog`.`Signature5Date`,
`intakelog`.`Signature6Date`,
`intakelog`.`UpdateDate`,
`intakelog`.`OrigID`
FROM `pantry`.`intakelog`
WHERE ID IN (SELECT
MAX(`intakelog`.`ID`)
FROM `pantry`.`intakelog`
GROUP BY `intakelog`.`OrigID`, DATE(`intakelog`.`UpdateDate`)
)) records


 ORDER BY OrigID, ID)
 dt
)dt1
WHERE version = 0
;
END $$

DELIMITER ;